### PR TITLE
Fix bot navmesh selection infelicities

### LINKED ISSUE #2850: Bug in bot navigation code (granger bots use dretch navcons)
https://p.mort.coffee/k20.png <- this is what happened in 0.52, if following patch is applied (to be able to force alien bots to be builders).
Currently, the granger uses the dretch's navmesh.

I may [produce nonsensical](https://github.com/DaemonEngine/Daemon/pull/957#issuecomment-1806676043) code, but when I refactor stuff, I try to limit myself on the number of bugs introduced, and even host my changes to spot more problems and fix them.
As people might remember, this is far from being the 1st problem I spot in that stuff. I will also refrain from providing a fix, since I write, you know, nonsensical code, anyway.

```
commit dc581bebe648b8b95d3f3735bc325ccb06da43fa
Author: Morel Bérenger <berengermorel76@gmail.com>
Date:   Sat Nov 11 20:10:55 2023 +0100

    mess with code so that it is possible to force bots as grangers

diff --git a/src/sgame/sg_bot.cpp b/src/sgame/sg_bot.cpp
index 09bf7fc51..71dd88941 100644
--- a/src/sgame/sg_bot.cpp
+++ b/src/sgame/sg_bot.cpp
@@ -521,9 +521,20 @@ void G_BotSpectatorThink( gentity_t *self )
 		}
 		else if ( teamnum == TEAM_ALIENS )
 		{
-			self->client->pers.classSelection = PCL_ALIEN_LEVEL0;
-			self->client->ps.stats[STAT_CLASS] = PCL_ALIEN_LEVEL0;
-			BotSetNavmesh( self, PCL_ALIEN_LEVEL0 );
+			if ( g_bot_level0.integer )
+			{
+				self->client->pers.classSelection = PCL_ALIEN_LEVEL0;
+			}
+			else if ( g_bot_advgranger.integer && BG_ClassUnlocked( PCL_ALIEN_BUILDER0_UPG ) )
+			{
+				self->client->pers.classSelection = PCL_ALIEN_BUILDER0_UPG;
+			}
+			else if ( g_bot_granger.integer )
+			{
+				self->client->pers.classSelection = PCL_ALIEN_BUILDER0;
+			}
+			self->client->ps.stats[STAT_CLASS] = self->client->pers.classSelection;
+			BotSetNavmesh( self, self->client->pers.classSelection );
 		}
 
 		G_PushSpawnQueue( &level.team[ teamnum ].spawnQueue, clientNum );
diff --git a/src/sgame/sg_bot_ai.cpp b/src/sgame/sg_bot_ai.cpp
index ee49983ef..080837729 100644
--- a/src/sgame/sg_bot_ai.cpp
+++ b/src/sgame/sg_bot_ai.cpp
@@ -1085,13 +1085,27 @@ AINodeStatus_t BotActionEvolve ( gentity_t *self, AIGenericNode_t* )
 			status = STATUS_SUCCESS;
 		}
 	}
-	else if ( BotCanEvolveToClass( self, PCL_ALIEN_LEVEL0 ) )
+	else if ( BotCanEvolveToClass( self, PCL_ALIEN_LEVEL0 ) && g_bot_level0.integer )
 	{
 		if ( BotEvolveToClass( self, PCL_ALIEN_LEVEL0 ) )
 		{
 			status = STATUS_SUCCESS;
 		}
 	}
+	else if ( BotCanEvolveToClass( self, PCL_ALIEN_BUILDER0 ) && g_bot_granger.integer )
+	{
+		if ( BotEvolveToClass( self, PCL_ALIEN_BUILDER0 ) )
+		{
+			status = STATUS_SUCCESS;
+		}
+	}
+	else if ( BotCanEvolveToClass( self, PCL_ALIEN_BUILDER0_UPG ) && g_bot_advgranger.integer )
+	{
+		if ( BotEvolveToClass( self, PCL_ALIEN_BUILDER0_UPG ) )
+		{
+			status = STATUS_SUCCESS;
+		}
+	}
 
 	return status;
 }
diff --git a/src/sgame/sg_extern.h b/src/sgame/sg_extern.h
index 102d4f1da..31d52a78d 100644
--- a/src/sgame/sg_extern.h
+++ b/src/sgame/sg_extern.h
@@ -187,6 +187,9 @@ extern vmCvar_t g_bot_lcannon;
 
 // bot evolution cvars
 extern vmCvar_t g_bot_evolve;
+extern vmCvar_t g_bot_granger;
+extern vmCvar_t g_bot_advgranger;
+extern vmCvar_t g_bot_level0;
 extern vmCvar_t g_bot_level1;
 extern vmCvar_t g_bot_level2;
 extern vmCvar_t g_bot_level2upg;
diff --git a/src/sgame/sg_main.cpp b/src/sgame/sg_main.cpp
index 3e2c622be..9be66985f 100644
--- a/src/sgame/sg_main.cpp
+++ b/src/sgame/sg_main.cpp
@@ -230,6 +230,9 @@ vmCvar_t g_bot_lcannon;
 
 // bot evolution cvars
 vmCvar_t g_bot_evolve;
+vmCvar_t g_bot_granger;
+vmCvar_t g_bot_advgranger;
+vmCvar_t g_bot_level0;
 vmCvar_t g_bot_level1;
 vmCvar_t g_bot_level2;
 vmCvar_t g_bot_level2upg;
@@ -427,6 +430,9 @@ static cvarTable_t gameCvarTable[] =
 
 	// bots: evolution
 	{ &g_bot_evolve, "g_bot_evolve", "1", CVAR_NORESTART, 0, false, nullptr },
+	{ &g_bot_granger, "g_bot_granger", "1", CVAR_NORESTART, 0, false, nullptr },
+	{ &g_bot_advgranger, "g_bot_advgranger", "1", CVAR_NORESTART, 0, false, nullptr },
+	{ &g_bot_level0, "g_bot_level0", "1", CVAR_NORESTART, 0, false, nullptr },
 	{ &g_bot_level1, "g_bot_level1", "1", CVAR_NORESTART, 0, false, nullptr },
 	{ &g_bot_level2, "g_bot_level2", "1", CVAR_NORESTART, 0, false, nullptr },
 	{ &g_bot_level2upg, "g_bot_level2upg", "1", CVAR_NORESTART, 0, false, nullptr },
```

### PR DESCRIPTION
**Pull request by slipher**
Fixes #2850.

### CODE REVIEW

File: src/sgame/botlib/bot_nav.cpp [hunk 1]
```diff
@@ -112,11 +112,34 @@ void G_BotEnableArea( const glm::vec3 &origin, const glm::vec3 &mins, const glm:
...
 }
 
-void G_BotSetNavMesh( int botClientNum, qhandle_t nav )
+void G_BotSetNavMesh( int botClientNum, class_t newClass )
 {
-	if ( nav < 0 || nav >= numNavData )
+	if ( newClass == PCL_NONE )
 	{
-		Log::Warn( "Navigation handle out of bounds" );
+		return;
```
Comment (DolceTriade) [inline src/sgame/botlib/bot_nav.cpp]: warn?

**Comment by sweet235** [comment]
LGTM by testing, didn't read carefully

File: src/sgame/botlib/bot_nav.cpp (hunk 1 above)
Comment (slipher) [reply src/sgame/botlib/bot_nav.cpp]: Warn what? The page only displays 1 context line and I can't figure out how to see the code this comment is attached to...

Comment (DolceTriade) [reply src/sgame/botlib/bot_nav.cpp]: You refactored the code so that this comment no longer applies. I meant don't silently return when no navmesh is found.

**Comment by DolceTriade** [comment]
lgtm

File: src/sgame/botlib/bot_load.cpp [hunk 2]
```diff
@@ -75,12 +75,12 @@ void BotAssertionInit()
...
 void BotSaveOffMeshConnections( NavData_t *nav )
 {
-	char filePath[ MAX_QPATH ];
 	fileHandle_t f = 0;
 
 	std::string mapname = Cvar::GetValue( "mapname" );
-	Com_sprintf( filePath, sizeof( filePath ), "maps/%s-%s.navcon", mapname.c_str(), nav->name );
-	trap_FS_FOpenFile( filePath, &f, fsMode_t::FS_WRITE );
+	std::string filePath = Str::Format(
+		"maps/%s-%s.navcon", mapname, BG_Class( nav->species )->name );
```
Comment (illwieckz) [inline src/sgame/botlib/bot_load.cpp:82]: Totally bikeshedding, but I believe having `"maps/%s-%s.navcon"` on the same line as `Str::Format(` would make it more readable.

Comment (illwieckz) [reply src/sgame/botlib/bot_load.cpp:82]: I believe it's better if at least the first argument is on the same line, except maybe specific rare situations where a bunch of arguments are all on their own lines, aligned.

In the same way, this looks wonky to me:

```
		Log::Notice(
			"Could not allocate Detour Navigation Mesh Query for navmesh %s", speciesName );
```

Comment (slipher) [reply src/sgame/botlib/bot_load.cpp]: Done
