### PR TITLE
rmlui: Bounds check the chat cursor.

### LINKED ISSUE #2138: reported crash: Unhandled exception out_of_range in basic_string
```
<Sweet> a player had a client crash while playing on human team, and reports this as the last output line:
<Sweet> Warn: CGame VM: Unhandled exception (St12out_of_range): basic_string
<Sweet> the player cannot remember what he did before that
<Sweet> that is all i know, so i don't think i should write an issue for that
```

### PR DESCRIPTION
**Pull request by DolceTriade**
We let you move the cursor forward every time you press right, even if it is already at the end of the string, this can allow you to go past the end of the string when you try to enter the next character which can lead to a crash.

Thanks to @sweet235 for the report and repro instructions.

Fixes #2138

### CODE REVIEW

**Comment by sweet235** [comment]
I run that on map testing server, can confirm that it fixes https://github.com/Unvanquished/Unvanquished/issues/2138

**Review by necessarily-equal — APPROVED** [review]
LGTM, haven't tested

**Comment by necessarily-equal** [comment]
Yay! Thanks for fixing this

File: src/cgame/rocket/rocketChatField.h [hunk 1]
```diff
@@ -284,6 +284,10 @@ class RocketChatField : public Rml::Element, Rml::EventListener
 
 	void MoveCursorForward()
 	{
+		if (cursor_character_index >= static_cast<size_t>( Q_UTF8_Strlen( text.c_str() ) ) )
```
Comment (slipher) [inline src/cgame/rocket/rocketChatField.h:287]: cursor_character_index is actually just a byte index. So you want text.size() not Q_UTF8_Strlen.

Comment (DolceTriade) [reply src/cgame/rocket/rocketChatField.h]: Ahh... I thought that cursor_character_index was the index of the character. I didn't look at the code closely enough. Thanks.
