### PR TITLE
fix target_push when angle is used instead of target

### LINKED ISSUE #1850: pusher entities which only set speed and angle are removed and thus do not work
I'll detail this issue more later.
For reference, a map to reproduce the problematic behavior was [made](https://github.com/UnvanquishedAssets/UnvanquishedTestAssets/tree/master/src/map-test-pushpad_src.dpkdir). The bug can also be seen in zittrig-arena from cu-kai.
On the test map, both jumpers are meant to work the same way. Zittrig-arena works fine in tremulous.

It seems the pusher (push1 in test map) is removed because it can not find what it is associated with.

_Edit by illwieckz:_ I put a better link and fixed typo in Kai's name.

### PR DESCRIPTION
**Pull request by bmorel**
fix #1850

### CODE REVIEW

File: src/sgame/sg_spawn_shared.cpp [hunk 1]
```diff
@@ -69,6 +69,14 @@ void think_aimAtTarget( gentity_t *self )
 	VectorAdd( self->r.absmin, self->r.absmax, origin );
 	VectorScale( origin, 0.5f, origin );
 
+	if ( false
```
Comment (DolceTriade) [inline src/sgame/sg_spawn_shared.cpp:72]: why

File: src/sgame/sg_spawn_shared.cpp [hunk 2]
```diff
@@ -69,6 +69,14 @@ void think_aimAtTarget( gentity_t *self )
...
+			|| self->s.origin2[0] != 0.f
```
Comment (DolceTriade) [inline src/sgame/sg_spawn_shared.cpp:73]: Do you need to compare with epsilon?

**Review by DolceTriade — CHANGES_REQUESTED** [review]

File: src/sgame/sg_spawn_shared.cpp (hunk 1 above)
Comment (bmorel) [reply src/sgame/sg_spawn_shared.cpp:72]: old trick of mine. Forgot to remove it from unv.
I usually do this when I have a `if` with long lines. This makes it possible to:

1. `yyp` in vim to quickly duplicate stuff,
2. alignment is made with tabs or space: don't care, it just works,
3. you can remove or add components of the if by touching a single line, reduce number of changes in git

File: src/sgame/sg_spawn_shared.cpp (hunk 2 above)
Comment (bmorel) [reply src/sgame/sg_spawn_shared.cpp:73]: No, because the values are set to 0 before. If it happens that something changed the value and all result in a 0 +- epsilon, then it means something was initialized and thus it's fine (but map is likely buggy).

File: src/sgame/sg_spawn_shared.cpp (hunk 1 above)
Comment (bmorel) [reply src/sgame/sg_spawn_shared.cpp:72]: Note that this would not have happened with a sane interface, instead of that horribly vec3_t.

**Review by DolceTriade — APPROVED** [review]
