### PR TITLE
[tinygettext] Fix language matching, compare to lowercase-d specs

### LINKED ISSUE #2938: Needs manual intervention for Chinese language support
I’d like to contribute some variants of Chinese translation, but I’ve found some problems.

After analyzing I came up with fixes. Pick one of these:

## The easy way

We *need* specific Chinese variants, namely `zh_CN`, `zh_HK` and `zh_TW`, but Weblate platform doesn’t have these:
(As for why *need*… see explanations later)
Screenshot_20240302_124913
Screenshot_20240302_125006

In the mean while, weblate says:
> This list includes only basic languages. Please contact project maintainers to add others.

So if maintainers are able to add those variants manually (and I can access them) the problem is solved.

## The hard way

As shown in screenshots above, Weblate do has Chinese variants called `zh_Hans`, `zh_Hant_HK`, and `zh_Hant`.
They loosely corresponds to `zh_CN`, `zh_HK` and `zh_TW`.

But the *code* doesn’t allow us to use `zh_Han*` correctly.

To fix, we need to patch (or vendor) the tinygettext library:
- Add `zh_Han*` variants to [`language.cpp`](https://github.com/Unvanquished/Unvanquished/blob/ae89e2591c1bf52ab8311e1f9dd43efd6cf9b65c/libs/tinygettext/src/language.cpp#L281):
```cpp
  { "zh", "Hans",     nullptr, "Chinese (simplified)"        },
  { "zh", "Hant_HK",  nullptr, "Chinese (Hong Kong)"         },
  { "zh", "Hant",     nullptr, "Chinese (traditional)"       },
```
- Work out a way to let the helper function [`convertFilename2Language`](https://github.com/Unvanquished/Unvanquished/blob/ae89e2591c1bf52ab8311e1f9dd43efd6cf9b65c/libs/tinygettext/src/dictionary_manager.cpp#L269) to don’t capitalize so-called “country specification” in these cases (`zh_HANS` is wrong, and makes all [matches](https://github.com/Unvanquished/Unvanquished/blob/ae89e2591c1bf52ab8311e1f9dd43efd6cf9b65c/libs/tinygettext/src/dictionary_manager.cpp#L136) score the same, all variants will use a same `.po` file)
  - In my mind, matching after making both filename and contrycode lowercase should be ok

## The unofficial way

I could also keep Chinese translations by myself in a git repository as a community effort.
(see [one of my similar work](https://github.com/NaitLee/xon-zh-grand-l10n), quality guaranteed 😉)
For this case you can have a dedicated dpk for distribution, if that’s acceptable.

### PR DESCRIPTION
**Pull request by NaitLee**
[tinygettext] Fix language matching, compare to lowercase-d specs, instead of forcibly making "country" spec uppercase (which could go wrong when that field isn’t really a country)

Fixes #2938 the hard way.

Note that this fix assumes that results from `Language::from_env` are only used for comparison to preset languages, rather than being used directly.

### CODE REVIEW

**Comment by NaitLee** [comment]
[From #2886](https://github.com/Unvanquished/Unvanquished/issues/2886#issuecomment-1872522333):
> We can't automatically detect country variants for now,

If I didn’t get it wrong, this is fixed too.

**Review by DolceTriade — COMMENTED** [review]
Does this break behavior for existing translations which don't have the country set?

**Comment by NaitLee** [comment]
> Does this break behavior for existing translations which don't have the country set?

No, the matching is simply made loose, current Unvanquished translations are working well.

I’d suggest to also give it some tests when upstreaming, for some other projects are using tinygettext too, and some among them have better translation support.

File: libs/tinygettext/src/dictionary_manager.cpp [hunk 1]
```diff
@@ -258,41 +258,6 @@ DictionaryManager::set_filesystem(std::unique_ptr<FileSystem> filesystem_)
 {
   filesystem = std::move(filesystem_);
 }
-// ----------------------------------------------------------------------------
-/** This function converts a .po filename (e.g. zh_TW.po) into a language
- *  specification (zh_TW). On case insensitive file systems (think windows)
- *  the filename and therefore the country specification is lower case
- *  (zh_tw). It Converts the lower case characters of the country back to
- *  upper case, otherwise tinygettext does not identify the country
- *  correctly.
```
Comment (DolceTriade) [inline libs/tinygettext/src/dictionary_manager.cpp:267]: this logic seems required no?

On windows the filenames could be `zh_hant_hk.po`

And thus won't be identified by tinygettext?

Comment (NaitLee) [reply libs/tinygettext/src/dictionary_manager.cpp:267]: You can see `Language::match` now compares language specs in lowercase.

For the purpose of `DictionaryManager::get_dictionary`, tinygettext compares pre-defined languages (they have correct cases) to languages from filenames, and then *uses a pre-defined language that is closest to the best file*. So we don’t really need to “correct” that so-called “country” spec, but rather match it loosely, ignoring case.

I’d test on Windows when I’m available. This fix works well on Linux (I have `zh_Han*.po` language files locally, that I’m working on)

Comment (DolceTriade) [reply libs/tinygettext/src/dictionary_manager.cpp:267]: Ah yes, I see.

**Review by DolceTriade — APPROVED** [review]

**Comment by sweet235** [comment]
This has been approved, and may be merged.

@NaitLee leave a comment if you want to merge this, I will do it.

File: libs/tinygettext/src/language.cpp [hunk 2]
```diff
@@ -281,6 +281,9 @@ static const LanguageSpec languages[] = {
   { "zh", "CN", nullptr, "Chinese (simplified)"        },
   { "zh", "HK", nullptr, "Chinese (Hong Kong)"         },
   { "zh", "TW", nullptr, "Chinese (traditional)"       },
+  { "zh", "Hans",     nullptr, "Chinese (simplified)"        },
+  { "zh", "Hant_HK",  nullptr, "Chinese (Hong Kong)"         },
+  { "zh", "Hant",     nullptr, "Chinese (traditional)"       },
```
Comment (illwieckz) [inline libs/tinygettext/src/language.cpp:286]: Isn't it confusing if the “long name” (in parenthesis) is the same as other values? Can those lang code be fully exchanged? Is zh_Hant always usable instead of zh_TW as a code for the same translation (and the reverse being true), basically zh_TW being an alias to zh_Hant?

Comment (NaitLee) [reply libs/tinygettext/src/language.cpp:286]: For `zh_Hans` the `Han` represents 「漢」“Chinese” and `s` for “simplified”. I think it is the `zh_CN` to be changed to `Chinese (China)` instead, because the `CN` part really means a country.

Which one to use depends on our choices of infrastructure (as the situation stated in #2938), and we only choose one between `zh_Hans` and `zh_CN`, as their difference can be disregarded after then.

I’d differentiate them as you said.

Comment (illwieckz) [reply libs/tinygettext/src/language.cpp]: Thanks.
